import { saveAs } from 'file-saver';

import { ROLE_LABELS } from './constants';
import { formatScore } from './score';
import type { ReportRow } from '../types';

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const LEFT = 36;
const TOP = 806;
const LINE_HEIGHT = 18;
const ROWS_PER_PAGE = 31;

interface PdfLine {
  text: string;
  x: number;
  y: number;
  size?: number;
  bold?: boolean;
}

function ascii(value: unknown): string {
  return String(value ?? '').replace(/[^\x20-\x7E]/g, '-');
}

function truncate(value: unknown, max: number): string {
  const text = ascii(value);
  return text.length > max ? `${text.slice(0, Math.max(0, max - 3))}...` : text;
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function textCommand(line: PdfLine): string {
  const font = line.bold ? 'F2' : 'F1';
  return `BT /${font} ${line.size ?? 10} Tf ${line.x} ${line.y} Td (${escapePdfText(line.text)}) Tj ET`;
}

function reportLines(rows: ReportRow[], title: string, subtitle: string): PdfLine[][] {
  const pages: PdfLine[][] = [];
  const safeTitle = truncate(title, 72);
  const safeSubtitle = truncate(subtitle, 90);
  const chunks = rows.length
    ? Array.from({ length: Math.ceil(rows.length / ROWS_PER_PAGE) }, (_, index) =>
        rows.slice(index * ROWS_PER_PAGE, (index + 1) * ROWS_PER_PAGE),
      )
    : [[]];

  for (const [pageIndex, pageRows] of chunks.entries()) {
    const lines: PdfLine[] = [
      { text: safeTitle, x: LEFT, y: TOP, size: 18, bold: true },
      { text: safeSubtitle, x: LEFT, y: TOP - 24, size: 10 },
      { text: `Page ${pageIndex + 1} of ${chunks.length}`, x: 500, y: TOP - 24, size: 9 },
      { text: 'Employee', x: LEFT, y: TOP - 58, bold: true },
      { text: 'Department', x: 172, y: TOP - 58, bold: true },
      { text: 'Tasks', x: 288, y: TOP - 58, bold: true },
      { text: 'Hours', x: 334, y: TOP - 58, bold: true },
      { text: 'Score', x: 382, y: TOP - 58, bold: true },
      { text: 'Status', x: 442, y: TOP - 58, bold: true },
    ];

    if (!pageRows.length) {
      lines.push({ text: 'No report rows match the selected filters.', x: LEFT, y: TOP - 86, size: 11 });
    }

    pageRows.forEach((row, index) => {
      const y = TOP - 86 - index * LINE_HEIGHT;
      lines.push(
        { text: truncate(row.employee.name, 23), x: LEFT, y },
        { text: truncate(row.employee.department || ROLE_LABELS[row.employee.role], 19), x: 172, y },
        { text: String(row.taskCount), x: 294, y },
        { text: row.totalHours.toFixed(1), x: 338, y },
        { text: formatScore(row.score), x: 382, y },
        { text: truncate(row.status.replace(/_/g, ' '), 16), x: 442, y },
      );
    });

    pages.push(lines);
  }

  return pages;
}

function buildPdf(pages: PdfLine[][]): Blob {
  const pageCount = pages.length;
  const fontId = 3 + pageCount * 2;
  const boldFontId = fontId + 1;
  const objects: string[] = [];

  objects[0] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[1] = `<< /Type /Pages /Kids [${pages.map((_, index) => `${3 + index * 2} 0 R`).join(' ')}] /Count ${pageCount} >>`;

  pages.forEach((lines, index) => {
    const pageId = 3 + index * 2;
    const contentId = pageId + 1;
    const stream = `${lines.map(textCommand).join('\n')}\n`;
    objects[pageId - 1] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] ` +
      `/Resources << /Font << /F1 ${fontId} 0 R /F2 ${boldFontId} 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId - 1] = `<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}endstream`;
  });

  objects[fontId - 1] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[boldFontId - 1] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

  let body = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(new TextEncoder().encode(body).length);
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = new TextEncoder().encode(body).length;
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    body += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([body], { type: 'application/pdf' });
}

export async function exportReportPdf(rows: ReportRow[], title: string, subtitle = 'Generated by WorkTrack'): Promise<void> {
  const blob = buildPdf(reportLines(rows, title, subtitle));
  const filename = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}.pdf`;
  saveAs(blob, filename || 'worktrack-report.pdf');
}
