import type { ReportRow } from '../types';

export async function exportReportPdf(rows: ReportRow[], title: string): Promise<void> {
  const [{ Document, Page, Text, View, StyleSheet, pdf }, { saveAs }] = await Promise.all([
    import('@react-pdf/renderer'),
    import('file-saver'),
  ]);

  const styles = StyleSheet.create({
    page: { padding: 28, backgroundColor: '#FFFFFF', color: '#111827', fontSize: 10 },
    title: { fontSize: 22, marginBottom: 6, fontWeight: 700 },
    subtitle: { color: '#4B5563', marginBottom: 18 },
    table: { display: 'flex', width: '100%' },
    row: { flexDirection: 'row', borderBottom: '1px solid #E5E7EB', paddingVertical: 8 },
    head: { backgroundColor: '#111827', color: '#FFFFFF', fontWeight: 700 },
    cell: { flex: 1, paddingHorizontal: 6 },
  });

  const ReportDocument = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>Generated by WorkTrack</Text>
        <View style={styles.table}>
          <View style={[styles.row, styles.head]}>
            <Text style={styles.cell}>Employee</Text>
            <Text style={styles.cell}>Role</Text>
            <Text style={styles.cell}>Tasks</Text>
            <Text style={styles.cell}>Hours</Text>
            <Text style={styles.cell}>Score</Text>
            <Text style={styles.cell}>Status</Text>
          </View>
          {rows.map((row) => (
            <View style={styles.row} key={row.employee.id}>
              <Text style={styles.cell}>{row.employee.name}</Text>
              <Text style={styles.cell}>{row.employee.role}</Text>
              <Text style={styles.cell}>{row.taskCount}</Text>
              <Text style={styles.cell}>{row.totalHours.toFixed(1)}</Text>
              <Text style={styles.cell}>{row.score === null ? '-' : `${Math.round(row.score)}%`}</Text>
              <Text style={styles.cell}>{row.status}</Text>
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );

  const blob = await pdf(ReportDocument).toBlob();
  saveAs(blob, `${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
}
